### ISSUE TITLE
Quad Rotation

### ISSUE THREAD

**Issue by lazarcl** [WhitmanCSCapstone/video-manipulation#18]
This might already be solved, so might wanna play around first. (see goal 2)

Goal 1: Right now quad rotation doesn't work. How can we get the executeHandlers to spin the tempBuffer? 

Goal 2: there are abstracted code snippets for rotation in PropertyHandler. Do these work and can we get them to work?

**Comment by ashleygw** [comment]
Current master now has x and y rotation enabled. For spinning there needs to be some variables with saved rotation value. Should those be in the same class? it would make things ez pz. Not using property handler tho

**Comment by ashleygw** [comment]
Rotating and fade is in. Did not use property handler because we want to draw in that method. Renaming drawtoScreen.
